### ISSUE TITLE
Possibility to enable or disable TineMCE for certain Name Spaces

### ISSUE THREAD

**Issue by jongfeli** [yaronkoren/TinyMCE#11]
This is more of a request. Default settings disable **TinyMCE** in the **Template** and the **Form** NS. 

Is it possible and feasible to make this configurable so any NS can be added to the exclusion list?

With different use cases this makes it a lot easier to prevent "bad" things from happening :-)

**Comment by yaronkoren** [comment]
Yes, a $wgTinyMCEDisabledNamespaces global variable would be good... or maybe just $wgTinyMCENamespaces, and have it be opt-in instead of opt-out? I'm not sure.

**Comment by duncan-crane** [comment]
I quite like the opt-in idea Yaron, provided we supply the user with some common defaults such as the main article workspace?

**Comment by jongfeli** [comment]
Thinking about this also made me more in favor of the **opt-in** option. It is then clear in which NS **TinyMCE** is working without the necessity to look up some custom or obscure NS to make sure it is disabled.

**Comment by yaronkoren** [comment]
@jongfeli - there is a certain logic to doing it that way... but the downside is that the default list of namespaces would have to be really long, I assume. I mean, if it's used by default for every namespace except "MediaWiki" and templates (which includes all the talk namespaces), that's almost 20 namespaces. Maybe that's not a problem, though.

**Comment by yaronkoren** [comment]
@duncan-crane, @jongfeli, anyone else - any thoughts?

**Comment by duncan-crane** [comment]
I see where you are coming from Yaron and I would be happy to go along with the approach you suggest.

**Comment by jongfeli** [comment]
Thinking about this again it seems that the **opt-out** is better for most use cases. It would result in a shorter list. And for the other cases the list is a bit longer, no problem.

**Comment by yaronkoren** [comment]
Okay, cool. I just added a $wgTinyMCEDisabledNamespaces variable, so I think is done now.

**Comment by jongfeli** [comment]
Works, below example disables **TinyMCE** in all but the MAIN namespace. Works in MW-1.27, 1.29 & 1.30. The nice thing about this is that on a disabled NS you can still use **TinyMCE** in a form. Now users can completely configure a wiki to there needs right up to page level with` __NOTINYMCE__ ` 

```php
#### TinyMCE extension
wfLoadExtension( 'TinyMCE' );
$wgTinyMCEDisabledNamespaces = array ( 
	NS_TALK,
	NS_USER,
	NS_USER_TALK,
	NS_PROJECT,
	NS_PROJECT_TALK,
	NS_IMAGE,
	NS_IMAGE_TALK,
	NS_FILE,
	NS_FILE_TALK,
	NS_MEDIAWIKI,
	NS_MEDIAWIKI_TALK,
	NS_TEMPLATE,
	NS_TEMPLATE_TALK,
	NS_HELP,
	NS_HELP_TALK,
	NS_CATEGORY,
	NS_CATEGORY_TALK
);
```

**Comment by dvsgnr** [comment]
Hello Everyone!

How can  **Template NS** be re-enabled  on TinyMCE?

Thanks before hand! )

**Comment by duncan-crane** [comment]
Hi Pierre
Thank you for trying out the TinyMCE extension.  
I think the reason TinyMCE is disabled for the TemplateNS was because template pages typically contain instructions to the wikiparser.  The TinyMCE editor would render these as if you were viewing the page rather than editing it.  For example people often put the template 'code' inside `<includeonly>` tags.  As a result the TinyMCE editor wouldn't display the code and so it would not be possible to edit it without using the 'raw' code editor window or the standard wikieditor.
Having said that, I don't think there is any other reason it can't be enabled.  Perhaps if you can explain a bit more about your 'use case' we could consider if this is the best way to achieve it?  You might also like to try placing your template wikitext in a normal page and editing it with the TinyMCE editor to see how it would be processed.
Many thanks

Duncan ~~~~
