### ISSUE TITLE
Need info for settings

### ISSUE THREAD

**Issue by TonyGravagno** [yaronkoren/TinyMCE#25]
I just started using this extension. I've looked through all other Q&A that I could find but have not found an answer. While this is a one-off question, please consider this ticket as a request to provide information in the README, the MW extension Talk page, or maybe in the GH wiki.

I added functions to LocalSettings.php to add macros which will add a Div tag and a Span tag. The Span tags get inserted, Div tags do not. I believe this is due to the built-in limit on valid_elements.

tinymce.js includes

      // Allow all elements and attributes if verify_html is set to false
      if (settings.verify_html === false) {
        settings.valid_elements = '*[*]';
      }

Exposing all tags and attributes may not be safe, so I found this JS line:

    var tinymce_extended_valid_elements = "div[id|dir|class|align|style],span[id|dir|class|align|style],ul[id|dir|class|align|style],li[id|dir|class|align|style]";

and I see that tinymce.js processes valid_elements and extended_valid_elements.

But what I'm missing is how we might send JavaScript "settings" values to tinymce.js. I modifed MW_tinymce.js, adding these assignments to the bottom of the array passed to init() :

    verify_html: false,
    valid_elements: '*[*]',
    extended_valid_elements: "div[id|dir|class|align|style],span[id|dir|class|align|style],ul[id|dir|class|align|style],li[id|dir|class|align|style]",

I know that's overkill - I'm just experimenting. It seems like those values are not used.

So:
1) What's the correct way to pass settings through this MW extension to TinyMCE?
2) How can I get a macro to insert a Div tag, rather than converting it to Span?
3) Is there already a small repository of information like this somewhere? Where?

Thanks.

**Comment by TonyGravagno** [comment]
Trying to answer the detail of my question:

To pass in a variable, from LocalSettings.php:
Set the variable in PHP as normal :

    $wgTinyMCETagList[] = 'div';

Then in ME_tinymce.js:

    wiki_tags_list: mw.config.get('wgTinyMCETagList'),

The mv.config.get function gets that variable and assigns it to the JS values which is then passed to TinyMCE init.

As to how to get a Div tag, I added Div to the back-end of this:

    additional_wiki_tags: '|ol|ul|li|h1|h2|h3|h4|h5|h6|ta|div',

Now I can manually insert a Div with the default MW editor, and it saves, and TinyMCE renders multiple lines in that Div within a box as a visual cue.

![image](https://user-images.githubusercontent.com/499473/40987601-c757790e-689d-11e8-9028-536a9f936eed.png)

But now it's Very difficult to get multiple lines within a Div to stay on different lines. I understand that MediaWiki (and browsers) render multi-line text on a single line. But the tool here shouldn't replace my newlines with spaces. In the above example, double clicking the box opens a code editor. On Save, the newlines are lost. I did this with the SyntaxHighlight tag (plugin activated) and the results were the same.

So for this ticket: I'm still not quite sure of the correct way to get a Div, though additional_wiki_tags seems to have done it. I answered the question about how to pass in config settings for TinyMCE. There's this new inquiry about not losing newlines. And then there is the question about where information like this should be documented. I'll be happy to bust this up into multiple tickets but these do inter-relate so for now I think it helps to keep this all in one place. Thanks.

**Comment by duncan-crane** [comment]
Hi Tony, just to let you know I have your tickets and will give you an initial response a little later.  Just got home from my day job so going to have my tea first :-)

**Comment by duncan-crane** [comment]
Hi Tony

Firstly, thank you for spending the time to try our extension and also for all your detective work.  

Without going into the detail of all the design decisions taken, the main challenge with this extension is aligning a number of different parsers which operate in, sometimes significantly, different ways.  These include the mediawiki parser, extension parser, TinyMCE parser and all the different browser dom parsers.  Because of this, it is rarely a simple question of enabling a tag in one and it behaving as expected in the 'round trip' between the different parsers.  

At some point in the process <div> tags were causing a problem so they  got removed and until now that hasn't been raised as a problem.  Clearly though they are now needed so I'll look into if we can make them work.  We've come a long way and hopefully I now have the techniques to make this possible without too much bother.  

It's because of the incompatibilities between the parsers that I decided not to expose the additional_wiki_tags config variable in LocalSettings.php as it could cause users problems.  But as I say, with the techniques we have developed to cope with some of the incompatibilities it may be possible to enable this now.  It may take me a few days to find the time to investigate but if you can leave it with me I may be able to find a solution.

One question I have is when you were trying the different options above did you try each on its own or did you have them all enable incrementally?  It may be that some of them conflict with the others.  In particular my proposal would be that only the change to the additional_wiki_tags variable should be used to enable the processing of additional tag.  

Many thanks

Duncan

**Comment by duncan-crane** [comment]
Hi @TonyGravagno 

You were on the right track with add div to additional_wiki_tags.  The problem was actually with the function for editing the wiki code snippet which was parsing it as html when it was saved rather than as wiki code.  This should now work ok if you'd like to try again.

I'm still not sure about making the additional_wiki_tags available in LocalSettings for the reasons given early about the complex interplay between the various parsers.  If there are other tags you think we need, let me know and I can see if they work OK. Technically it should be possible now to just enable them through the additional_wiki_tags variable, but I can't guarantee there won't be any unwanted side effects without testing them.

By the way we are in the process of moving the code to the Mediawiki Git/Gerrit repository so at some point soon you will need to go there to get updates.  This will be available through the extension's home page.

Many thanks
Duncan

**Comment by duncan-crane** [comment]
Hi @TonyGravagno and @yaronkoren 
I am proposing a change that replaces the additional_wiki_tags variable in MW_tinymce.js with a new global variable $wgTinyMCEAdditionalWikiTags which can be set in the LocalSettings.php file.  This global variable can contain an array of tags, for example:
```
$wgTinyMCEAdditionalWikiTags = array ( 
	ol,
	ul,
	li,
	h1,
	h2,
	h3,
	h4,
	h5,
	h6,
	ta,
	div
);
```
Any wiki text contained within tags listed in $wgTinyMCEAdditionalWikiTags will not be converted to html in the TinyMCE editor, including the tags themselves.  Instead the tagged wiki text will be displayed as parsed wiki text in a non editable box.  
In the TinyMCE editor, the content of the tagged wiki text will only be editable as  using the `{ ; }` or `< >`  menu buttons, as for any other non editable wiki code.  
If you are happy with this proposal I will upload this patch to the master on mediawiki git and update the documentation.  
As I have currently coded it, the tags listed in $wgTinyMCEAdditionalWikiTags will now be treated as html tags unless the user adds them to their LocalSettings.php file.  This will be a change to the default behaviour of the current version.  Please let me know if you think this is OK or otherwise if you think any of the tags should always not be processed as html.  If so I will add these to the list of wiki tags which are always ignored.
Many thanks
Duncan

**Comment by yaronkoren** [comment]
@duncan-crane - sorry for the long delay on this. Could you explain why you think this list should be a global variable? I looked through the discussion but didn't really understand a lot of it. Why should this set be different across different wikis?

**Comment by duncan-crane** [comment]
Hi @yaronkoren 

Thanks for your question.  Currently there is a configuration variable 'additional_wiki_tags' in MW_tinymce.js which allows the user to tell TinyMCE to ignore certain html tags that are embedded in the wikicode.  This has the effect that these tags (and any code contained within them) are not processed when parsed from wikicode to html and back again.  Instead they are treated as 'wikimagic' code.  For the benefit of readers unfamiliar with 'wikimagic' code, this is displayed in TinyMCE as a if it was process by the mediawiki parser behind a non-editable box.  The code can be edited by selecting the '< >' or '{ ; }' menu buttons.  This allows TinyMCE to handle templates, parser function and allowable html tags etc.
 
The list of html tags in the 'additional_wiki_tags' variable is not a complete list of all the html tags that mediawiki allows in wiki code, and I couldn't find a single global with a complete list.  The choice was just the list I felt was most likely to meet the needs of most authors.  

I understand Tony's request is that he wanted to add to this list, with the <div> tag.  He also pointed out that different users might wish to extend (or shorten) this list to suite their needs.  To illustrate this Johnywhy on the extension talk page seemed to be asking that all html tags are disallowed, which means the html wiki TinyMCE parser would convert allowed html tags to their wikicode equivalent (for example h? or li tags).

Tony's request is that the 'additional_wiki_tags' configuration variable be moved from  MW_tinymce.js  to LocalSettings.php.  This doesn't seem unreasonable, as one probably shouldn't expect users to have to change the extension elsewhere to achieve what they want.  It is also quite straightforward to make this change.

There are other options, eg trying to identify all the allowable html tags in wikicode and configure TinyMCE to accept these, and leave the user to decide through how they enter the code on each page to decide whether they use html tags or wikicode.  This may make it more difficult to maintain the extension though, as it means being able to identify all such allowable html tags and changing the list if any are added (or removed) from mediawiki.

I'm sorry for the long explanation but it is a fairly technical topic.  Do let me know if you need any more explanation or have any other suggestions.

Many thanks 

Duncan

**Comment by yaronkoren** [comment]
@duncan-crane - okay, thanks; now I understand it a lot better. You put in a "div" tag that's not visible, but I get what you were saying. :) This seems like a good change, then. But is there a better name for the variable "$wgTinyMCEAdditionalWikiTags"? I know it's based on a setting called "additional_wiki_tags", but it's not very clear what this variable does. (I'm not sure "additional_wiki_tags" is a great name either, for the same reason.)

**Comment by duncan-crane** [comment]
Hi @yaronkoren 
Good point.  How about $wgTinyMCEConservedHtmlTags or $wgTinyMCEHtmlTagsPreservedInWikicode.  You can see I don't have a lot of imagination when it comes to naming things so I'm open to suggestions :-)
Duncan

**Comment by yaronkoren** [comment]
@duncan-crane - what do you think of $wgTinyMCEPreservedTags for the name? It's a little "snappier" than the other name ideas, but maybe it doesn't convey enough?

**Comment by duncan-crane** [comment]
This change has now been added to Git/Gerrit and the documentation updated.

**Comment by TonyGravagno** [comment]
Swinging back after a long respite from MW challenges. Thanks for the continued interest and changes. Your time, consideration, and effort are all sincerely appreciated.
